a=int(input("Enter 1st number: "))
b=int(input("Enter 2nd number: "))
print("Sum: ",a+b)
print("Difference: ",a-b)
print("Product: ",a*b)
print("Quotient (a/b): ",a/b)
print("Remainder (a%b): ",a%b)
